### ISSUE TITLE
Request to work on documentation

### ISSUE THREAD

**Issue by dmcanelly** [unitedstates/congress-votes-servo#1]
I'd like to work on this project, I'm a new coder and need to get started working on F/OSS projects. 
I'd like to turn in data in this repo into a web app that tracks the most recent votes in Congress. 
What, if any, documentation does this project need? I noticed the lack of a README file. 
How is the data in this repo collected?

**Comment by JoshData** [comment]
Hello,

This repo is really just to log changes in official vote data, since records are sometimes revised without Congress telling anyone. This repo is basically just a scratch space for me to audit the records.

See https://github.com/unitedstates/congress for scripts to fetch the data and https://www.govtrack.us/developers and https://sunlightfoundation.com/api/ for live data sources. You should re-ask your question in those places. :)

**Comment by dmcanelly** [comment]
Thanks, I've been looking at /unitedstates/congress and I've started to play with the Sunlight API, this data collection is exactly what I need so I had to ask! :) Thank you for your time.
